**NumPy Basics**



In [8]:
import numpy as np

Creating a Python list and converting it to numpy array

In [11]:
new_list = [1, 2, 3, 4]
new_list

[1, 2, 3, 4]

In [13]:
np.array(new_list)

array([1, 2, 3, 4])

In [17]:
next_list = [[1, 2, 3, 4], [5, 6, 7, 8]]
next_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
np.array(next_list)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Built-in Methods**

1. arange(Return evenly spaced values with a given inverval)

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

2. zeros and ones creates arrays of zeros and ones

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# in case of 2-D array pass the values within a tuple

In [32]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3. linspace(Return evenly spaced numbers over a specified interval)

In [45]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [47]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

4. eye(creates identity matrix)

In [50]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Random**

5. rand(create an array of the given shape and populate it with random samples from a uniform distribution over 0 to 1)

In [54]:
np.random.rand(10)

array([0.18528652, 0.10177709, 0.44040272, 0.11867168, 0.4426744 ,
       0.10520854, 0.37437323, 0.97637999, 0.22943498, 0.05775561])

# in case of we don't want to pass as a tuple

In [61]:
np.random.rand(4, 4)

array([[0.84555126, 0.31457508, 0.34004961, 0.16507706],
       [0.27107538, 0.11259104, 0.04432593, 0.25329703],
       [0.08416069, 0.05608234, 0.31486409, 0.05775539],
       [0.98334501, 0.61500293, 0.36200929, 0.56937262]])

6. randn(Return a sample(or samples from the "standard normal" distribution. Unlike rand which is uniform)

In [64]:
np.random.randn(10)

array([-1.28274511,  0.95122351,  0.76263671,  0.9583586 , -0.08712771,
       -0.04155977, -2.30117971, -1.27150827, -0.3109106 , -0.29518643])

In [66]:
np.random.randn(5, 5)

array([[-0.00331691,  0.29336227, -0.76369923,  0.11825556, -0.18460911],
       [-0.3659993 , -1.31990696,  1.63291313,  0.73342177,  1.568059  ],
       [-1.09215068, -0.98933014, -0.59962904,  1.05325833,  1.43993562],
       [-0.08330876, -1.92106445,  0.39796182, -1.40150915, -1.08285847],
       [-1.39574613, -0.20111456,  1.41909319, -0.48654308,  0.79819798]])

7. randint(Return random integers from low to high(exclusive))

In [69]:
np.random.randint(10)

6

In [71]:
np.random.randint(1, 40, 20)

array([10, 37, 12, 33, 25, 36, 12, 35, 29,  5, 22, 17, 31,  5, 21, 28, 36,
       16,  2,  3])

**Array attributes and method**

In [80]:
arr = np.arange(20)
random_array = np.random.randint(0, 60, 12)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [84]:
random_array

array([44, 28, 20, 31, 57, 48, 49, 24, 29, 10, 30, 22])

8. reshape(Returns an array containing the same data with a new shape)

In [95]:
arr.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

9. min, max, argmin, argmax

In [100]:
random_array.min()

10

In [102]:
random_array.argmin() # index of the smallest element

9

In [104]:
random_array.max()

57

In [106]:
random_array.argmax()

4

10. shape(shape is an attribute that arrays have(not a method, no paranthesis))

In [111]:
arr.shape

(20,)

In [114]:
arr.reshape(1, 20).shape

(1, 20)

11. dtype(data type)

In [117]:
arr.dtype

dtype('int32')