In [1]:
import numpy as np

In [16]:
arr = np.arange(0, 20, 2)

In [18]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**Array slicing**

In [20]:
arr[3]

6

In [22]:
arr[1:6]

array([ 2,  4,  6,  8, 10])

**Broadcasting**

Numpy arrays differ from a normal Python list because of their ability to broadcast

In [26]:
arr[0:5] = 10

In [28]:
arr

array([10, 10, 10, 10, 10, 10, 12, 14, 16, 18])

In [36]:
# Resetting the array
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
slice_of_arr = arr[1:5]
slice_of_arr

array([2, 4, 6, 8])

In [52]:
slice_of_arr[:] = 25
slice_of_arr

array([25, 25, 25, 25])

In [54]:
arr

array([ 0, 25, 25, 25, 25, 10, 12, 14, 16, 18])

# Here the arr array is also  

# for copying data use copy()

In [59]:
arr_copy = arr.copy()
arr_copy

array([ 0, 25, 25, 25, 25, 10, 12, 14, 16, 18])

**2-D array indexing**

In [66]:
arr_2d = np.arange(1,51).reshape(5, 10)
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [68]:
arr_2d[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [70]:
arr_2d[1][1]

12

In [72]:
arr_2d[1,1]

12

In [76]:
# for getting last 3 columns
arr_2d[:,7:]

array([[ 8,  9, 10],
       [18, 19, 20],
       [28, 29, 30],
       [38, 39, 40],
       [48, 49, 50]])

**Selection**(Based of comparison operator)

In [82]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
# The above operation can be done in one single step
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])